version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html

  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default:/etc/nginx/conf.d/default.conf
    links:
      - app
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erwincrm
      MYSQL_USER: crmdbuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    links:
      - db

volumes:
  mysql_data:
